"""Download the web fonts into public/fonts so the site makes zero third-party
requests (no Google Fonts call = visitors' IPs aren't sent anywhere, and the
Content-Security-Policy can stay 'self'-only). All fonts are SIL OFL.

Usage: python3 scripts/fetch-fonts.py
"""
import re, pathlib, urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600"
           "&family=Playfair+Display:ital,wght@0,400;0,600;1,400"
           "&family=Sarabun:wght@400;500&family=Noto+Sans+Khmer:wght@400;500&display=swap")
KEEP = {"latin", "thai", "khmer"}  # unicode subsets we actually render
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36"

def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()

css = get(CSS_URL).decode()
out_dir = pathlib.Path("public/fonts"); out_dir.mkdir(parents=True, exist_ok=True)
blocks = re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
kept = []
for subset, block in blocks:
    if subset not in KEEP:
        continue
    fam = re.search(r"font-family: '([^']+)'", block).group(1).replace(" ", "")
    style = re.search(r"font-style: (\w+)", block).group(1)
    weight = re.search(r"font-weight: (\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    name = f"{fam}-{weight}{'i' if style == 'italic' else ''}-{subset}.woff2"
    path = out_dir / name
    if not path.exists():
        path.write_bytes(get(url))
    kept.append(f"/* {subset} */\n" + block.replace(url, f"fonts/{name}"))
pathlib.Path("public/fonts.css").write_text("/* Generated by scripts/fetch-fonts.py (SIL OFL fonts). */\n" + "\n".join(kept) + "\n")
print(f"{len(kept)} font faces -> public/fonts.css")
