"""Generate public/layouts.js from the system's xkb Thai symbols file.

xkb's `th` file is the authoritative source for both layouts on Linux
(`basic` = Kedmanee, `pat` = Pattachote), so we derive the web mapping from it
instead of hand-typing ~94 characters and risking a silent typo.

Usage: python3 scripts/gen-layouts.py
"""
import json, re, pathlib

XKB = pathlib.Path("/usr/share/X11/xkb/symbols/th").read_text()
KEYSYMDEF = pathlib.Path("/usr/include/X11/keysymdef.h").read_text()

# xkb key name -> KeyboardEvent.code
CODES = {"TLDE": "Backquote", "BKSL": "Backslash"}
for i, c in enumerate(["Digit1","Digit2","Digit3","Digit4","Digit5","Digit6","Digit7","Digit8","Digit9","Digit0","Minus","Equal"], 1):
    CODES[f"AE{i:02d}"] = c
for i, c in enumerate("QWERTYUIOP", 1):
    CODES[f"AD{i:02d}"] = "Key" + c
CODES["AD11"], CODES["AD12"] = "BracketLeft", "BracketRight"
for i, c in enumerate("ASDFGHJKL", 1):
    CODES[f"AC{i:02d}"] = "Key" + c
CODES["AC10"], CODES["AC11"] = "Semicolon", "Quote"
for i, c in enumerate("ZXCVBNM", 1):
    CODES[f"AB{i:02d}"] = "Key" + c
CODES["AB08"], CODES["AB09"], CODES["AB10"] = "Comma", "Period", "Slash"

# keysym name -> unicode char, from the "/* U+XXXX */" comments in keysymdef.h
SYM = {}
for m in re.finditer(r"#define XK_(\w+)\s+0x[0-9a-f]+\s+/\*[ (]*U\+([0-9A-F]{4})", KEYSYMDEF):
    SYM[m.group(1)] = chr(int(m.group(2), 16))

def resolve(tok):
    tok = tok.strip()
    if tok.startswith("0x100"):
        return chr(int(tok, 16) - 0x1000000)
    return SYM[tok]

def layout(variant):
    body = re.search(r'xkb_symbols "%s" \{(.*?)\n\};' % variant, XKB, re.S).group(1)
    out = {}
    for m in re.finditer(r"key <(\w+)>\s*\{\s*\[\s*([^\]]+)\]", body):
        normal, shifted = [resolve(t) for t in m.group(2).split(",")[:2]]
        out[CODES[m.group(1)]] = [normal, shifted]
    assert len(out) == 47, (variant, len(out))
    return out

layouts = {"kedmanee": layout("basic"), "pattachote": layout("pat")}
js = ("// Generated by scripts/gen-layouts.py from xkb's Thai symbols. Do not edit.\n"
      "// Each entry: KeyboardEvent.code -> [unshifted, shifted].\n"
      "export const LAYOUTS = " + json.dumps(layouts, ensure_ascii=False, indent=1) + ";\n")
pathlib.Path("public/layouts.js").write_text(js)
print("wrote public/layouts.js")
for k, v in layouts.items():
    print(k, "".join(v[c][0] for c in ["KeyA","KeyS","KeyD","KeyF","KeyG","KeyH","KeyJ","KeyK","KeyL","Semicolon"]))
