"""Generate public/layouts.js from the system's xkb symbol files.

xkb is the authoritative source for these layouts on Linux (th `basic` =
Kedmanee, th `pat` = Pattachote, kh `basic` = Khmer NiDA), so we derive the
web mapping from it instead of hand-typing hundreds of characters and risking
a silent typo.

Usage: python3 scripts/gen-layouts.py
"""
import json, re, pathlib

SYMBOLS = pathlib.Path("/usr/share/X11/xkb/symbols")
# name -> (xkb file, variant, levels to keep). Level 3 is AltGr (right Alt).
LAYOUTS = {
    "kedmanee": ("th", "basic", 2),
    "pattachote": ("th", "pat", 2),
    "nida": ("kh", "basic", 3),
}
# The kh file uses unassigned code points U+17FB..U+17FF as placeholders for
# keys that type a vowel plus a sign in one press (NiDA standard).
COMPOSED = {
    0x17FB: "\u17BB\u17C7",  # ុះ
    0x17FC: "\u17BB\u17C6",  # ុំ
    0x17FD: "\u17C1\u17C7",  # េះ
    0x17FE: "\u17C4\u17C7",  # ោះ
    0x17FF: "\u17B6\u17C6",  # ាំ
}
KEYSYMDEF = pathlib.Path("/usr/include/X11/keysymdef.h").read_text()

# xkb key name -> KeyboardEvent.code
CODES = {"TLDE": "Backquote", "BKSL": "Backslash"}
for i, c in enumerate(["Digit1","Digit2","Digit3","Digit4","Digit5","Digit6","Digit7","Digit8","Digit9","Digit0","Minus","Equal"], 1):
    CODES[f"AE{i:02d}"] = c
for i, c in enumerate("QWERTYUIOP", 1):
    CODES[f"AD{i:02d}"] = "Key" + c
CODES["AD11"], CODES["AD12"] = "BracketLeft", "BracketRight"
for i, c in enumerate("ASDFGHJKL", 1):
    CODES[f"AC{i:02d}"] = "Key" + c
CODES["AC10"], CODES["AC11"] = "Semicolon", "Quote"
for i, c in enumerate("ZXCVBNM", 1):
    CODES[f"AB{i:02d}"] = "Key" + c
CODES["AB08"], CODES["AB09"], CODES["AB10"] = "Comma", "Period", "Slash"

# keysym name -> unicode char, from the "/* U+XXXX */" comments in keysymdef.h
SYM = {}
for m in re.finditer(r"#define XK_(\w+)\s+0x[0-9a-f]+\s+/\*[ (]*U\+([0-9A-F]{4})", KEYSYMDEF):
    SYM[m.group(1)] = chr(int(m.group(2), 16))

def resolve(tok):
    tok = tok.strip()
    if tok == "voidsymbol":
        return None
    if tok.startswith("0x100"):
        cp = int(tok, 16) - 0x1000000
        return COMPOSED.get(cp, chr(cp))
    if len(tok) == 1:
        return tok
    return SYM[tok]

def layout(file, variant, levels):
    xkb = (SYMBOLS / file).read_text()
    body = re.search(r'xkb_symbols "%s" \{(.*?)\n\};' % variant, xkb, re.S).group(1)
    out = {}
    for m in re.finditer(r"key <(\w+)>\s*\{\s*\[\s*([^\]]+)\]", body):
        if m.group(1) not in CODES:
            continue  # space bar and modifiers are handled by the app
        chars = [resolve(t) for t in m.group(2).split(",")[:levels]]
        while chars and chars[-1] is None:
            chars.pop()
        out[CODES[m.group(1)]] = chars
    assert len(out) == 47, (variant, len(out))
    return out

layouts = {name: layout(*spec) for name, spec in LAYOUTS.items()}
js = ("// Generated by scripts/gen-layouts.py from xkb's Thai symbols. Do not edit.\n"
      "// Each entry: KeyboardEvent.code -> [unshifted, shifted, altgr?]. A value\n"
      "// can be two characters (Khmer keys that type a vowel plus a sign).\n"
      "export const LAYOUTS = " + json.dumps(layouts, ensure_ascii=False, indent=1) + ";\n")
pathlib.Path("public/layouts.js").write_text(js)
print("wrote public/layouts.js")
for k, v in layouts.items():
    print(k, " ".join(v[c][0] for c in ["KeyA","KeyS","KeyD","KeyF","KeyG","KeyH","KeyJ","KeyK","KeyL","Semicolon"]))
